import {
  WalletIcon,
  ShopIcon,
  TagIcon,
  CodeDocumentIcon,
  CodeCircleIcon,
  TranslateIcon,
  StoryIcon,
  NoteIcon,
  PeopleIcon,
  WalletAddIcon,
  SmsTrackingIcon,
  CartIcon,
  ShareIcon,
  GalleryIcon,
  MessageIcon,
  MusicPlaylistIcon,
} from '@/components/icons/bold-icons';

export const FEATURE_SELECTION_TITLE = 'Discover blogging platforms by choosing a feature';
export const FEATURES: Feature[] = [
  'Ad Monetization',
  'Category & Tag System',
  'Code Export',
  'Code Inject',
  'Comment System',
  'E-commerce',
  'Figma Integration',
  'Image Optimization',
  'Integrated Reader Base',
  'Markdown',
  'Newsletter',
  'Open-source',
  'Paywall',
  'Sell Digital Products',
];

export const FEATURE_ICONS = {
  'Ad Monetization': WalletIcon,
  'Category & Tag System': TagIcon,
  'Code Export': CodeDocumentIcon,
  'Code Inject': CodeCircleIcon,
  'Comment System': MessageIcon,
  'E-commerce': CartIcon,
  'Figma Integration': StoryIcon,
  'Image Optimization': GalleryIcon,
  'Integrated Reader Base': PeopleIcon,
  Markdown: NoteIcon,
  Newsletter: SmsTrackingIcon,
  'Open-source': ShareIcon,
  Paywall: WalletAddIcon,
  'Sell Digital Products': MusicPlaylistIcon,
};

export const FEATURE_COLORS = {
  'Ad Monetization': 'green',
  'Category & Tag System': 'violet',
  'Code Export': 'violet',
  'Code Inject': 'violet',
  'Comment System': 'iris',
  'E-commerce': 'jade',
  'Figma Integration': 'pink',
  'Image Optimization': 'iris',
  'Integrated Reader Base': 'plum',
  Markdown: 'iris',
  Newsletter: 'purple',
  'Open-source': 'plum',
  Paywall: 'teal',
  'Sell Digital Products': 'jade',
};
export const FEATURE_CATEGORY_COLORS: { [FeatureCategory: string]: Color } = {
  Technical: 'violet',
  Monetization: 'cyan',
  Content: 'crimson',
  Design: 'pink',
};
