// DEFAULT DATA LOADING CONSTANTS
export const PLATFORMS_PARAMS_SORT_BY = 'order' as any;
export const PLATFORMS_PARAMS_EXTENDED = false;

export const DEFAULT_PLATFORMS_LOADING_PARAMS = {
  sort_by: PLATFORMS_PARAMS_SORT_BY,
  extended: PLATFORMS_PARAMS_EXTENDED,
};
